---
title: "CRIME INCIDENCE IN DC"
author: "Cherry"
date: "10/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Chapter 1 - INTRODUCTION

The crime incidence in the US is one of the most discussed issues in the country. Although the Federal Bureau of Investigation (FBI) in its 2018 report found an overall decline in violent and property crimes in 2018, there has been more media releases of increasing crime incidence in the US, especially mass shootings in recent periods. Increased incidence of crime is a threat to public safety and welfare. At the national level, violent crime and homicide rates increased from 2014 to 2016, but rate remain near historical lows compared to rates in the 90’s. 

Washington DC saw an increase in murder rate by 35.6 percent in 2018. (Brennan Center for Justice). Between 2017 and 2018, of all the types of crimes, homicide rates in DC increased the most by about 38%, followed by auto theft which increased by 13%. There was a decrease in other crimes such as sex abuse, assualt and robbery.

This report focuses on all reported crimes in the DC metro police system which includes violent crime, theft, arson, assault, homicide, sex abuse, and burglary. These crimes can be categorized into violent crime and property crime. Violent crime refers to murder, robbery, rape and aggravated assault. Property crime includes burglary, larceny-theft, and motor vehicle theft. Murder includes murder and non-negligent manslaughter. Total crime incidence includes all the above. 

The rest of this report contains 6 chapters - chapter 2 includes the description of data (source, definition of variables and geographic coverage), chapter 3 includes the crime types and methods, chapter 4 analyses the relationship between time and crime, chapter 5 describes the spatial distribution of crime in DC and chapter 6 presents a conclusion of the report.


## Chapter 2 - Description of Data

### 2.1 - Source of the data

The source data for our exploratory data analysis is a CSV containing crime incident data in DC for 2018. This data was sourced from Kaggle. The CSV contains over 30,000 crime incidence with reported data and time of incidence, method/weapon used, offence classification for the crime, the location of the crime (block, ward, neighbourhood, voting_precinct, latitude and longitude), start date, end date and record ID. 

### 2.2 - Definition of the variables in the dataset

For context, homicide in this report refers to the killing of a person purposely, or otherwise, with a malicious aforethought. Sexual abuse as engaging in or causing another person to submit to a sexual act by force, threat or fear. Arson refers to malicious burning or attempt to burn a property, structure, vessel or vehicle of another person. Robbery refers to the act of taking anything of value from another person by force, fear or violence. Assault can be defined as purposely or knowingly causing serious bodily injury, threatening to do so or engaging in any act that creates a risk of physical injury to another person. Burglary is the unlawful entry into a property with the intent to commit a criminal offence. The report date is the date the offense was reported to the police which may be later than the date the incident occurred (DC metropolitan police department). 


